development:
  adapter: postgresql
  encoding: utf8
  database: stackoverflow_development
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: stackoverflow_test
  host: localhost

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
