development:
  adapter: postgresql
  encoding: utf8
  database: stackoverflow_development
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: stackoverflow_test
  host: localhost
